### ISSUE TITLE
Consider using Clippy

### ISSUE THREAD

**Issue by pmarcelll** [H2CO3/PHiLe#2]
[Clippy](https://github.com/Manishearth/rust-clippy) is a linter for Rust.

**Comment by H2CO3** [comment]
Yep, I've seen Clippy, and I have already considered using it since I'm not a fan of Rust's lenience with regards to shadowing (I've been bitten multiple times by unintentional shadowing in other languages), but that apparently can't be turned off, and Clippy seems to have a warning pass for it.

However, from what I can tell, its installation is not very easy and it also puts some requirements on my build environment, hence I didn't yet set it up. I have to gather all my courage for that 🤣

**Comment by pmarcelll** [comment]
There's an easy way to use it:

- `cargo install clippy` (with a nightly compiler)
  - if you're using rustup, you can type `cargo +nightly install clippy` instead
- `cargo clippy` in your project folder

**Comment by H2CO3** [comment]
That's the problem: I'd rather use a stable compiler, not the nightly one, and Clippy seems to require the nightly.
